# Generated by Django 4.1 on 2022-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('birthdate', models.TimeField()),
                ('dni', models.FloatField(unique=True)),
                ('alive', models.BooleanField()),
            ],
        ),
    ]
