# Generated by Django 4.1 on 2022-12-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField(max_length=100, unique=True)),
                ('usage', models.BooleanField()),
            ],
        ),
    ]
