# Generated by Django 4.1 on 2022-12-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
